ALTER TABLE lobby RENAME COLUMN state TO status;
ALTER TABLE lobby ALTER COLUMN status TYPE varchar(30);
ALTER TABLE lobby ADD COLUMN started_at TIMESTAMP;
ALTER TABLE lobby ADD COLUMN paused_at TIMESTAMP;
ALTER TABLE lobby ADD COLUMN IF NOT EXISTS owner_id INT REFERENCES player(id);
